baseURL = "http://example.org/"
languageCode = "en-us"
title = "Hellracers"
theme = "hellracers"

[menu]
    [[menu.main]]
        identifier = "News"
        name = "News"
        title = "blog section"
        url = "/news/"
        weight = -120
    
    [[menu.main]]
        identifier = "drivers"
        name = "Drivers"
        title = "blog section"
        url = "/drivers/"
        weight = -110

    [[menu.main]]
        identifiers = "who-are-we"
        name = "Who are we?"
        title = "Who are we?"
        url = "/who-are-we/"
        weight = -100

    [[menu.main]]
        identifiers = "results"
        name = "Results"
        title = "Results"
        url = "/results/"
        weight = -90
    
    [[menu.contact]]
        name = "Email"
        url = "mailto:hellracerssweden@gmail.com" 

    [[menu.social]]
        name = "Facebook"
        url = "https://facebook.com"
        weight = -110
    
    [[menu.social]]
        name = "Twitter"
        url = "https://twitter.com"
        weight = -100

    [[menu.social]]
        name = "Instagram"
        url = "https://instagram.com/hellracers_sweden"
        weight = -90
    
    [[menu.partners]]
        name = "Pixeldust"
        url = "https://pixeldust.se"
        weight = -110

    [[menu.partners]]
        name = "Craigs Setup Shop"
        url = "https://craigsetupshop.co.uk"
        weight = -100

    [[menu.partners]]
        name = "Barncancerfonden"
        url = "https://barncancerfonden.se"
        weight = -90


    
