baseURL = "http://hellracers.se/"
languageCode = "en-us"
title = "Hellracers"
theme = "hellracers"
og_image = "/img/hellracers-footer-logo.png"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
    [[menu.main]]
        identifier = "News"
        name = "News"
        title = "blog section"
        url = "/news/"
        weight = -120
    
    [[menu.main]]
        identifier = "drivers"
        name = "Drivers"
        title = "blog section"
        url = "/drivers/"
        weight = -110

    [[menu.main]]
        identifiers = "who-we-are"
        name = "Who we are"
        title = "Who we are"
        url = "/who-we-are/"
        weight = -100

    [[menu.main]]
        identifiers = "live"
        name = "Live"
        title = "Live"
        url = "/live"
        weight = -90
    
    [[menu.contact]]
        name = "Email"
        url = "mailto:hellracerssweden@gmail.com" 

    [[menu.social]]
        name = "Facebook"
        url = "https://facebook.com/hellracers.se"
        weight = -110
    
    [[menu.social]]
        name = "Twitter"
        url = "https://twitter.com/hellracers_se"
        weight = -100

    [[menu.social]]
        name = "Instagram"
        url = "https://instagram.com/hellracers.se"
        weight = -90
    
    [[menu.partners]]
        name = "Pixeldust"
        url = "https://pixeldust.se"
        weight = -110
    
    [[menu.partners]]
        name = "Tershine"
        url = "https://tershine.com"
        weight = -100

    [[menu.partners]]
        name = "Craigs Setup Shop"
        url = "https://craigsetupshop.co.uk"
        weight = -90

    [[menu.partners]]
        name = "Barncancerfonden"
        url = "https://barncancerfonden.se"
        weight = -80


    
